steps:
  -   name: 'gcr.io/cloud-builders/git'
      entrypoint: 'bash'
      args: [ '-c', 'git fetch --unshallow --tags && git checkout ${BRANCH_NAME} && git submodule init && git submodule update' ]

  -   name: 'taktik/git-version:2.0.8-gb47b2d0e35'
      args: [ '-f', 'git.version' ]

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: [ '-c', 'echo ${_DOCKER_PASSWORD} | docker login --username=${_DOCKER_USERNAME} --password-stdin' ]

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: ['-c', 'docker buildx create --name multiarch --driver docker-container --use']

  -   name: 'docker:24-git'
      entrypoint: 'sh'
      args: [ '-c', 'docker build --progress=plain -f build.Dockerfile -t "icureio/cardinal:$(cat git.version)" --build-arg "repoUsername=$$REPO_USERNAME" --build-arg "repoPassword=$$REPO_PASSWORD" . && docker push "icureio/cardinal:$(cat git.version)"' ]
      secretEnv: [ 'REPO_USERNAME', 'REPO_PASSWORD' ]

  - name: 'docker:24-git'
    entrypoint: 'sh'
    args: [ '-c', 'docker build --builder multiarch --progress=plain -f package.Dockerfile --platform linux/amd64,linux/arm64 -t icureio/cardinal:latest -t icureio/cardinal:$(cat ./git.version) --build-arg "version=$(cat ./git.version)" . && docker push icureio/cardinal:latest && docker push icureio/cardinal:$(cat ./git.version)' ]

availableSecrets:
  secretManager:
    - versionName: projects/taktik-dev/secrets/ci-repo-username/versions/1
      env: 'REPO_USERNAME'
    - versionName: projects/taktik-dev/secrets/ci-repo-password/versions/1
      env: 'REPO_PASSWORD'

timeout: 2700s
