on:
  push:
    branches:
      - "ci/bump-common-and-kmehr-1.0.84-g97d4441b0a-202411081142"
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  licenses_report:
    name: Generating licenses report
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Creating licenses report
        env:
          ORG_GRADLE_PROJECT_repoUsername: ${{ secrets.REPO_USERNAME }}
          ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.REPO_PASSWORD }}
        run: ./gradlew generateLicenseReport -x build -x jar -x :kraken-common:core:generateLicenseReport

      - name: Copy, rename, and remove header
        run: tail -n +2 ./lite-core/build/reports/dependency-license/licenses.csv > ./${{ github.event.repository.name }}.csv

      - name: Setup Git
        run: |
          git config --global user.name "icure-dev"
          git config --global user.email "dev@icure.com"

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPO_DEPLOY_KEY }}"

      - name: Publish file to licenses-report
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git clone git@github.com:icure/licenses-report.git
          cd licenses-report
          mv ../${{ github.event.repository.name }}.csv ./java_kotlin/${{ github.event.repository.name }}.csv
          git add ./java_kotlin/${{ github.event.repository.name }}.csv
          STATUS=$(git status --porcelain)
          if [ -n "$STATUS" ]; then
            git commit -m "Update ${{ github.event.repository.name }}.csv"
            git push
          fi
